services:
    app:
        build:
            context: './backend/docker/local'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'larapipline-app'
        container_name: larapipline-app
        restart: unless-stopped
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            WWWUSER: '${WWWUSER}'
            XDEBUG_MODE: '${XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            SUPERVISOR_PHP_COMMAND: "/usr/sbin/php-fpm8.4 -F"
        volumes:
            - './backend:/var/www/html'
        networks:
            - larapipline
        depends_on:
            - pgsql
            - redis
            - minio

    web:
        image: nginx:alpine
        container_name: larapipline-web
        restart: unless-stopped
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - './backend:/var/www/html'
            - './backend/docker/local/nginx/default.conf:/etc/nginx/conf.d/default.conf'
        networks:
            - larapipline
        depends_on:
            - app

    worker:
        build:
            context: './backend/docker/local'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'larapipline-worker'
        container_name: larapipline-worker
        restart: unless-stopped
        environment:
            WWWUSER: '${WWWUSER}'
            SUPERVISOR_PHP_COMMAND: "php /var/www/html/artisan horizon"
        volumes:
            - './backend:/var/www/html'
        networks:
            - larapipline
        depends_on:
            - app
            - pgsql
            - redis

    frontend:
        build:
            context: './frontend'
            dockerfile: docker/local/Dockerfile
        image: 'larapipline-frontend'
        container_name: larapipline-frontend
        restart: unless-stopped
        ports:
            - '3000:3000'
        volumes:
            - './frontend:/app'
            - '/app/node_modules'
        networks:
            - larapipline

    pgsql:
        image: 'postgres:18-alpine'
        container_name: larapipline-pgsql
        restart: unless-stopped
        ports:
            - '${DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-password}'
            POSTGRES_DB: '${DB_DATABASE:-central}'
            POSTGRES_USER: '${DB_USERNAME:-root}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-password}'
        volumes:
            - 'larapipline-pgsql:/var/lib/postgresql/data'
        networks:
            - larapipline
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
            retries: 3
            timeout: 5s

    redis:
        image: 'redis:alpine'
        container_name: larapipline-redis
        restart: unless-stopped
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'larapipline-redis:/data'
        networks:
            - larapipline
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s

    minio:
        image: 'devkandil/minio:latest'
        container_name: larapipline-minio
        restart: unless-stopped
        ports:
            - '${FORWARD_MINIO_PORT:-9000}:9000'
            - '${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900'
        environment:
            MINIO_ROOT_USER: '${MINIO_ROOT_USER:-admin}'
            MINIO_ROOT_PASSWORD: '${MINIO_ROOT_PASSWORD:-password}'
        volumes:
            - 'larapipline-minio:/data'
        networks:
            - larapipline
        command: 'minio server /data --console-address ":8900"'
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            retries: 3
            timeout: 5s

    mailpit:
        image: 'axllent/mailpit:latest'
        container_name: larapipline-mailpit
        restart: unless-stopped
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - larapipline

networks:
    larapipline:
        name: larapipline-network
        driver: bridge
volumes:
    larapipline-pgsql:
        name: larapipline-pgsql
        driver: local
    larapipline-redis:
        name: larapipline-redis
        driver: local
    larapipline-minio:
        name: larapipline-minio
        driver: local